-- ============================================================================
-- Migration 0004: POS & Checkout Console (Sales Context)
-- Mosaiz Mundo ERP
--
-- Creates:
--   * orders            (idempotency anchor: UNIQUE (organization_id,
--                        client_offline_id) — docs/pos_offline.md §1)
--   * order_items       (line items, engine-verified to share the parent
--                        order's organization)
--   * app.process_pos_checkout(jsonb) — idempotent checkout entry point
--
-- Conventions (CLAUDE.md): organization_id + user_belongs_to_org RLS policy
-- and app.set_updated_at trigger on every operational table; ENABLE (never
-- FORCE) RLS; explicit guarded grants for mosaiz_app_user.
--
-- Depends on: 0001 (organizations, app.* helpers), 0003 (procedure grant
-- conventions)
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- orders — one row per completed POS checkout
-- ----------------------------------------------------------------------------
CREATE TABLE public.orders (
    id                uuid           PRIMARY KEY DEFAULT gen_random_uuid(),
    -- No ON DELETE CASCADE from organizations: orders are financial ledger
    -- rows; tenant offboarding must handle them deliberately, not silently.
    organization_id   uuid           NOT NULL REFERENCES public.organizations (id),
    -- UUIDv4 generated by the POS client while offline; the retry key.
    client_offline_id uuid           NOT NULL,
    status            text           NOT NULL DEFAULT 'completed'
                                     CHECK (status IN ('completed', 'voided')),
    -- No equality check against the items sum: discounts, service charges and
    -- rounding are client-side concerns until the pricing engine lands.
    total_amount      numeric(10,2)  NOT NULL CHECK (total_amount >= 0),
    created_at        timestamptz    NOT NULL DEFAULT now(),
    updated_at        timestamptz    NOT NULL DEFAULT now(),

    -- The idempotency engine: an offline POS retrying a dropped request can
    -- never double-book a sale (docs/pos_offline.md §1).
    UNIQUE (organization_id, client_offline_id),
    -- Composite target for order_items' FK so a line item provably belongs
    -- to the same organization as its parent order.
    UNIQUE (id, organization_id)
);

CREATE INDEX orders_org_created_at_idx
    ON public.orders (organization_id, created_at);

COMMENT ON TABLE public.orders IS
    'POS checkouts. (organization_id, client_offline_id) unique = idempotent retries.';
COMMENT ON COLUMN public.orders.client_offline_id IS
    'UUIDv4 minted by the POS client (offline-capable); retrying the same checkout is a no-op.';

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();

-- ----------------------------------------------------------------------------
-- order_items — line items of an order
--
-- Carries organization_id per the Golden Rule (docs/rls_policies.md §1) even
-- though it is derivable via orders: RLS stays uniform and cheap, and the
-- composite FK makes a cross-tenant parent/child mismatch impossible at the
-- engine level.
-- ----------------------------------------------------------------------------
CREATE TABLE public.order_items (
    id                uuid           PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id          uuid           NOT NULL,
    organization_id   uuid           NOT NULL,
    -- Raw uuid for now; the FK to the menu/sellable-items table arrives with
    -- the inventory context migration.
    sellable_item_id  uuid           NOT NULL,
    quantity          integer        NOT NULL CHECK (quantity > 0),
    unit_price        numeric(10,2)  NOT NULL CHECK (unit_price >= 0),
    created_at        timestamptz    NOT NULL DEFAULT now(),
    updated_at        timestamptz    NOT NULL DEFAULT now(),

    FOREIGN KEY (order_id, organization_id)
        REFERENCES public.orders (id, organization_id)
        ON DELETE CASCADE
);

CREATE INDEX order_items_order_id_idx ON public.order_items (order_id);

COMMENT ON TABLE public.order_items IS
    'Order line items. Composite FK guarantees the line shares its parent order''s organization.';

CREATE TRIGGER trg_order_items_updated_at
    BEFORE UPDATE ON public.order_items
    FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();

-- ----------------------------------------------------------------------------
-- Row Level Security — standard user_belongs_to_org on both tables
-- ----------------------------------------------------------------------------
ALTER TABLE public.orders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items  ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_belongs_to_org ON public.orders
    FOR ALL
    USING      (app.user_belongs_to_org(organization_id))
    WITH CHECK (app.user_belongs_to_org(organization_id));

CREATE POLICY user_belongs_to_org ON public.order_items
    FOR ALL
    USING      (app.user_belongs_to_org(organization_id))
    WITH CHECK (app.user_belongs_to_org(organization_id));

-- ----------------------------------------------------------------------------
-- app.process_pos_checkout — idempotent checkout entry point
--
-- Deliberately SECURITY INVOKER (the default), unlike provision_new_tenant:
-- checkout must NOT cross the RLS boundary. Running with the caller's
-- privileges means the user_belongs_to_org WITH CHECK verifies the payload's
-- organization_id against the authenticated session — a forged cross-tenant
-- payload is rejected by the engine, with no manual filtering (per
-- docs/rls_policies.md agent instruction).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE app.process_pos_checkout(payload jsonb)
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
    v_org_id   uuid    := (payload ->> 'organization_id')::uuid;
    v_coid     uuid    := (payload ->> 'client_offline_id')::uuid;
    v_total    numeric := (payload ->> 'total_amount')::numeric;
    v_items    jsonb   := payload -> 'items';
    v_order_id uuid;
BEGIN
    IF v_org_id IS NULL OR v_coid IS NULL OR v_total IS NULL THEN
        RAISE EXCEPTION
            'checkout payload must include organization_id, client_offline_id and total_amount';
    END IF;
    IF v_items IS NULL OR jsonb_typeof(v_items) <> 'array'
       OR jsonb_array_length(v_items) = 0 THEN
        RAISE EXCEPTION 'checkout payload must include a non-empty items array';
    END IF;

    INSERT INTO public.orders (organization_id, client_offline_id, total_amount)
    VALUES (v_org_id, v_coid, v_total)
    ON CONFLICT (organization_id, client_offline_id) DO NOTHING
    RETURNING id INTO v_order_id;

    -- Retry of an already-processed checkout (docs/pos_offline.md §1):
    -- succeed silently, insert nothing, never double-book.
    IF v_order_id IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO public.order_items
        (order_id, organization_id, sellable_item_id, quantity, unit_price)
    SELECT
        v_order_id,
        v_org_id,
        (item ->> 'sellable_item_id')::uuid,
        (item ->> 'quantity')::integer,
        (item ->> 'unit_price')::numeric
    FROM jsonb_array_elements(v_items) AS item;
END;
$$;

COMMENT ON PROCEDURE app.process_pos_checkout(jsonb) IS
    'Idempotent POS checkout: retrying the same (organization_id, client_offline_id) '
    'is a silent no-op. SECURITY INVOKER on purpose — RLS validates the org.';

REVOKE ALL ON PROCEDURE app.process_pos_checkout(jsonb) FROM PUBLIC;

-- ----------------------------------------------------------------------------
-- Grants for the application role. No DELETE: orders are an accounting-grade
-- ledger — a sale is voided (status UPDATE), never erased.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'mosaiz_app_user') THEN
        GRANT SELECT, INSERT, UPDATE
            ON public.orders, public.order_items
            TO mosaiz_app_user;
        GRANT EXECUTE ON PROCEDURE app.process_pos_checkout(jsonb)
            TO mosaiz_app_user;
    END IF;
END;
$$;

COMMIT;
